### ISSUE TITLE
Migration to travis-ci.com

### ISSUE THREAD

**Issue by knorth55** [PR2/app_manager#32]
app_manager is disabled in travis-ci.com?
https://travis-ci.com/github/PR2/app_manager

and it's running ci in travis-ci.org now.
https://travis-ci.org/github/PR2/app_manager

we need to switch to `travis-ci.com` because `travis-ci.org` will be disabled soon.

**Comment by v4hn** [comment]
Actually,

Travis support in Github became worse and worse over time and many projects I know migrated to GitHub Actions by now.
Because the PR2 repositories are so low-traffic they still work, but I don't know for how long...
I don't know whether @k-okada considers this migration for the PR2 repositories, but mostly someone would have to do the work...

**Comment by k-okada** [comment]
ok, done https://travis-ci.com/github/PR2/app_manager/builds/228696895
--
◉ Kei Okada



2021年6月11日(金) 17:59 Michael Görner ***@***.***>:

**Comment by knorth55** [comment]
thank you!
